/**
* @File Name : testApexClasss.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 20, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 20, 2024 |   | Initial Version
**/

public class testApexClasss {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}